(defun post-header (title)
  (interactive)
  (insert "---\n")
  (insert "layout: post\n")
  (insert (concat "title: " title))(insert "\n")
  (insert "---\n")
  )

(defun new-post (title)
  (interactive "sBlog Post Title: ")
  (defvar title title)
  (find-file (concat (concat "/home/epl692/posts/" (concat (format-time-string "%Y-%m-%d-") (replace-regexp-in-string "[!@#$%^&*()_+\.,<>:'`\\]" "" (replace-regexp-in-string " " "-" title)))) ".md"))
  (post-header title)
  )

(global-set-key (kbd "C-x p") `new-post)
